### ISSUE TITLE
Not an issue: feedback levels

### ISSUE THREAD

**Issue by JerryI** [davidcann/electron-trackpad-utils#1]
Thank you for your library!
I was looking for something that simple for ages. It levels up user experience a lot when is is used with sliders and some other UI elements.

Just as a suggestion. Is it possible to vary the haptic feedback? like light medium and strong?

Also a question. How bad is it to call feedback function quite often? Could it potentially damage coils? Hope Apple did test it properly for such cases.

**Comment by davidcann** [comment]
These are the very limited options for haptic feedback from Apple:
https://developer.apple.com/documentation/appkit/nshapticfeedbackpattern?language=objc

Here's where it's set in the code (hard-coded to NSHapticFeedbackPatternAlignment):
https://github.com/davidcann/electron-trackpad-utils/blob/08fceac06cc6090993f17d68a04e695dc9d413e7/addon.mm#L118

I hard-coded it mainly to keep things simple, but also because the options aren't very interesting.

> Also a question. How bad is it to call feedback function quite often? Could it potentially damage coils? Hope Apple did test it properly for such cases.

I haven't seen Apple saying that it could cause a hardware problem, just mainly a user experience issue, I think.

**Comment by JerryI** [comment]
Thanks, @davidcann !

I will try to play around with this.
